### ISSUE TITLE
This extension is looks similar to you

### ISSUE THREAD

**Issue by hmphu** [keyata/keyata#22]
@coliff  Today I found this extension: https://github.com/borismus/keysocket https://smus.com/chrome-media-keys-revisited/ 

The source code is super similar your.

**Comment by coliff** [comment]
Yes, that one is the original. I based this extension on that. Keysocket had a message up that it is no longer supported and is looking for a new maintainer... As the code is open-source I decided to make a hard fork of the project and add a bunch of new services, tidy up the code, add new icon and rename it.
